### ISSUE TITLE
Removed files, now what?

### ISSUE THREAD

**Issue by ramonck** [smysnk/gulp-cloudfront#11]
Hey guys,

So I removed my files to try to upload it again to s3 using gulp-cloudfront, and now I'm busted.

I tried it a couple of times and it always says that my files are "cached" or "found". How do I clear all of it out and upload everything again in my bucket? I tried creating a new bucket, new cloudfront and it seems that the caching or mapping is somewhere in my PC.

Best Regards,

**Comment by smysnk** [comment]
> So I removed my files to try to upload it again to s3 using gulp-cloudfront, and now I'm busted.
I am a bit confused by this statement, it suggests you believe that gulp-cloudfront will upload your files to s3.  This plugin is purely for interacting with cloudfront, not s3.

As per all the examples, awspublish performs the function of uploading to a s3 bucket.

**Comment by ramonck** [comment]
Hi,

So let me explain in details, what's going on:
1) I uploaded all files using gulp-cloudfront with awspublish, revall...
2) I then decided to remove all files from S3 and run the process again.
3) When I ran the script from gulp it always says that the file has an "entry" or is "cached"
4) Therefore it's not replicating to the S3 bucket
5) Even when removing the bucket or removing the Cloudfront and creating a new one it's not fixing.

(That was yesterday and this morning)
-----------------------------------------------------------------------------
Today:

1) I removed my local "dist" folder 
2) Runned the cloudfront process with awspublish so I can maybe clear up the cached files from whereever they're cached, keep on getting "found reference"
3) regenerated using Gulp in "dist"
4) Ran the cloudfront process again with awspublish..
5) It created the files now...

There's still come crazy caching going on somewhere :)


But I still have problem from yesterday, my index file didn't get its references updated :(

**Comment by ramonck** [comment]
My index file did get it's name updated: index.2e6ac32e.html

But the references inside are incorrect.

I see that the references in my css files did get updated correctly.

I see that the references in my js files got updated correctly

I see that the files that are in the revall ignore rule don't get the links/resources updated, I don't want the name changed but I want the references ok :).

**Comment by smysnk** [comment]
publisher.cache()
Create a through stream that create or update a cache file using file s3 path and file etag. Consecutive runs of publish will use this file to avoid reuploading identical files.

Cache file is save in the current working dir and is named .awspublish-<bucket>. The cache file is flushed to disk every 10 files just to be safe.

--

Not related gulp-cloudfront.
