### ISSUE TITLE
Index.html reference not getting updated

### ISSUE THREAD

**Issue by ramonck** [smysnk/gulp-cloudfront#12]
My index file did get it's name updated: index.2e6ac32e.html

But the references inside are incorrect.

I see that the references in my css files did get updated correctly.

I see that the references in my js files got updated correctly

I see that the files that are in the revall ignore rule don't get the links/resources updated, I don't want the name changed but I want the references ok :).

**Comment by ramonck** [comment]
OBS: My index.html is not in revall ignore rule.

**Comment by smysnk** [comment]
Not a gulp-cloudfront issue.
