### ISSUE TITLE
Pattern is hardcoded to 8 character hashes

### ISSUE THREAD

**Issue by thoradam** [smysnk/gulp-cloudfront#13]

**Comment by smysnk** [comment]
options.patternIndex

Type: Regular Expression Default: /^\/index\.[a-f0-9]{8}\.html(\.gz)*$/gi

Specify the pattern used to match the default root object

var aws = {
    ..,
    "patternIndex": /^\/root\-[a-f0-9]{4}\.html(\.gz)*$/gi
};
