### ISSUE TITLE
Recommendation for deleting old files on s3?

### ISSUE THREAD

**Issue by stursby** [smysnk/gulp-cloudfront#20]
I've got `gulp-cloudfront` working correctly, however, I'm wondering what the best way to remove the old files on s3 is, since every time I push code, I know have multiple copies of all the same files.

I'm using [gulp-s3-ls](https://github.com/cworsley4/gulp-s3-ls), not [gulp-awspublish](https://github.com/pgherveou/gulp-awspublish) (because gulp-awspublish wasn't working for buckets with periods in the name...)

Any suggestions?

**Comment by levithomason** [comment]
You need to sync the local dir with s3.  It doesn't look like gulp-s3-ls supports sync.  The aws cli does extremely simply, so does gulp-awspublish if you can get that to work with your setup.

In either case, you probably want to ask this on SO for the best chance of getting help.
