### ISSUE TITLE
IMPORTANT! Outdated AWS SDK exposes issue with sSLSupportMethod being set to 'VIP'

### ISSUE THREAD

**Issue by remie** [smysnk/gulp-cloudfront#27]
Starting mid-October 2018 there is a confirmed issue with the AWS API when used in combination with older SDK versions (before at least 2015-09-17). This issue causes the CloudFront distribution that is updated using the `UpdateDistribution` to switch the supported SSL method from 'SNI only' to 'Virtual IP', regardless of the request parameters.

As shown in this CloudTrail Event:

```
{
    "eventVersion": "1.03",
    ...
    "eventSource": "cloudfront.amazonaws.com",
    "eventName": "UpdateDistribution",
    ...
    "userAgent": "aws-sdk-nodejs/2.0.31 linux/v6.8.1",
    "requestParameters": {
        "distributionConfig": {
            ...
            "viewerCertificate": {
                "sSLSupportMethod": "sni-only",
                "minimumProtocolVersion": "TLSv1"
            },
            ...
        }
    },
    "responseElements": {
        ...
        "distribution": {
            "distributionConfig": {
                ...
                "viewerCertificate": {
                    "sSLSupportMethod": "vip",
                    "minimumProtocolVersion": "TLSv1"
                },
                ...
            }
        }
    },
    ...
    "eventType": "AwsApiCall",
    "apiVersion": "2014_10_21",
    ...
}
```

the distribution request does have the correct value of the  `sSLSupportMethod`, but the response from the API says it was changed to VIP. This will incur additional costs up to $600,-- USD per distribution per month.

The only way to avoid this issue is to update to the latest version of the SDK. Amazon Web Services is aware of the issue and has created an internal request to stop support for older SDK, which will eventually break this package.

**Comment by joewoodhouse** [comment]
@remie please make a PR for this, this issue has just cost us $800! (not your fault - thanks for finding it!)

**Comment by remie** [comment]
@joewoodhouse created pull request (#28). Make sure to contact AWS support as you can probably get a refund due to the fact that this is a known issue with their API.

**Comment by joewoodhouse** [comment]
@remie amazing thanks. Yea we already had 1 refund from them last month, before we worked out what was causing this. Hoping they'll give us another one now we know it's a known issue. You don't happen to have a reference to this issue in their API do you? Is there a tracker entry or similar?
